/**
 * Plain-language substitutions, after the US federal plain language
 * guidelines and similar style guides.
 *
 * Every entry has to be safe in context. Words that are also common nouns
 * ("purchase", "attempt", "objective") are only replaced in the verb
 * positions that make the meaning certain, and anything that would need
 * grammar knowledge to get right is left alone rather than guessed at.
 */

import type { Rule } from "./text";

/** Whole-word, case-insensitive, global. */
export const word = (from: string) => new RegExp(`\\b${from.replace(/ /g, "\\s+")}\\b`, "gi");

const pairs = (list: [string, string][]): Rule[] => list.map(([from, to]) => [word(from), to]);

/** Wordy phrases → short ones. Also used by the "Concise" rewrite. */
export const WORDY_PHRASES: Rule[] = [
  [/\b(?:please be advised that|it should be noted that|it is important to note that|please note that|it goes without saying that|needless to say,?)\s*/gi, ""],
  ...pairs([
    ["in order to", "to"],
    ["so as to", "to"],
    ["due to the fact that", "because"],
    ["owing to the fact that", "because"],
    ["in view of the fact that", "because"],
    ["in light of the fact that", "because"],
    ["on the grounds that", "because"],
    ["despite the fact that", "although"],
    ["in spite of the fact that", "although"],
    ["regardless of the fact that", "although"],
    ["at this point in time", "now"],
    ["at this moment in time", "now"],
    ["at the present time", "now"],
    ["at the present moment", "now"],
    ["in the near future", "soon"],
    ["at an early date", "soon"],
    ["in the event that", "if"],
    ["in the event of", "in case of"],
    ["on the condition that", "if"],
    ["for the purpose of", "for"],
    ["with the exception of", "except"],
    ["with regard to", "about"],
    ["with respect to", "about"],
    ["in regard to", "about"],
    ["in relation to", "about"],
    ["in reference to", "about"],
    ["concerning the matter of", "about"],
    ["in accordance with", "following"],
    ["in close proximity to", "near"],
    ["a large number of", "many"],
    ["a great number of", "many"],
    ["a significant number of", "many"],
    ["the vast majority of", "most"],
    ["the majority of", "most"],
    ["a majority of", "most"],
    ["a sufficient number of", "enough"],
    ["a small number of", "a few"],
    ["has the ability to", "can"],
    ["have the ability to", "can"],
    ["has the capacity to", "can"],
    ["is able to", "can"],
    ["are able to", "can"],
    ["is required to", "must"],
    ["are required to", "must"],
    ["it is necessary to", "you must"],
    ["prior to", "before"],
    ["subsequent to", "after"],
    ["in excess of", "more than"],
    ["until such time as", "until"],
    ["on a daily basis", "daily"],
    ["on a weekly basis", "weekly"],
    ["on a monthly basis", "monthly"],
    ["on a regular basis", "regularly"],
    ["make a decision", "decide"],
    ["made a decision", "decided"],
    ["make an assessment of", "assess"],
    ["give consideration to", "consider"],
    ["take into consideration", "consider"],
    ["come to a conclusion", "conclude"],
    ["conduct an investigation into", "investigate"],
    ["conduct an investigation", "investigate"],
    ["provide assistance to", "help"],
    ["provide assistance", "help"],
    ["make a payment", "pay"],
    ["make an application", "apply"],
    ["each and every", "every"],
    ["first and foremost", "first"],
    ["absolutely essential", "essential"],
    ["end result", "result"],
    ["final outcome", "outcome"],
    ["past history", "history"],
    ["advance planning", "planning"],
    ["basic fundamentals", "fundamentals"],
    ["close proximity", "nearness"],
    ["future plans", "plans"],
    ["unexpected surprise", "surprise"],
    ["whether or not", "whether"],
    ["the reason why is that", "because"],
    ["in lieu of", "instead of"],
    ["per annum", "a year"],
  ]),
];

/** Formal or Latinate words → everyday ones. */
export const PLAIN_WORDS: Rule[] = [
  // Verb-only positions for words that are also nouns.
  [/\b(to|will|can|may|must|should|could|would|shall|please)\s+(purchase)\b/gi, (m, a) => `${a} buy`],
  [/\b(attempt|endeavou?r)\s+to\b/gi, (m) => (m[0] === m[0].toUpperCase() ? "Try to" : "try to")],
  ...pairs([
    ["aforementioned", "above"],
    ["accomplish", "do"],
    ["accomplished", "done"],
    ["additional", "more"],
    ["additionally", "also"],
    ["approximately", "about"],
    ["ascertain", "find out"],
    ["assist", "help"],
    ["assists", "helps"],
    ["assisted", "helped"],
    ["assistance", "help"],
    ["commence", "start"],
    ["commences", "starts"],
    ["commenced", "started"],
    ["commencement", "start"],
    ["consequently", "so"],
    ["deleterious", "harmful"],
    ["demonstrate", "show"],
    ["demonstrates", "shows"],
    ["demonstrated", "showed"],
    ["disseminate", "share"],
    ["dissemination", "sharing"],
    ["documentation", "documents"],
    ["elucidate", "explain"],
    ["expedite", "speed up"],
    ["expeditious", "fast"],
    ["expeditiously", "quickly"],
    ["extraneous", "outside"],
    ["facilitate", "help"],
    ["facilitates", "helps"],
    ["frequently", "often"],
    ["furthermore", "also"],
    ["heretofore", "until now"],
    ["impediment", "obstacle"],
    ["impediments", "obstacles"],
    ["implement", "carry out"],
    ["implemented", "carried out"],
    ["indicate", "show"],
    ["indicates", "shows"],
    ["initial", "first"],
    ["initially", "at first"],
    ["initiate", "start"],
    ["initiated", "started"],
    ["locate", "find"],
    ["magnitude", "size"],
    ["methodology", "method"],
    ["mitigate", "reduce"],
    ["modify", "change"],
    ["modification", "change"],
    ["modifications", "changes"],
    ["notwithstanding", "despite"],
    ["numerous", "many"],
    ["obtain", "get"],
    ["obtained", "got"],
    ["optimal", "best"],
    ["optimum", "best"],
    ["possess", "have"],
    ["possesses", "has"],
    ["preclude", "prevent"],
    ["previously", "earlier"],
    ["proficiency", "skill"],
    ["relocate", "move"],
    ["remainder", "rest"],
    ["remedial", "corrective"],
    ["remuneration", "pay"],
    ["repercussions", "effects"],
    ["require", "need"],
    ["requires", "needs"],
    ["requiring", "needing"],
    ["reside", "live"],
    ["resides", "lives"],
    ["retain", "keep"],
    ["retains", "keeps"],
    ["retained", "kept"],
    ["shall", "must"],
    ["stipulation", "condition"],
    ["stipulations", "conditions"],
    ["subsequently", "later"],
    ["substantial", "large"],
    ["substantially", "greatly"],
    ["sufficient", "enough"],
    ["terminate", "end"],
    ["terminated", "ended"],
    ["transmit", "send"],
    ["transmitted", "sent"],
    ["transpire", "happen"],
    ["transpires", "happens"],
    ["utilise", "use"],
    ["utilize", "use"],
    ["utilises", "uses"],
    ["utilizes", "uses"],
    ["utilised", "used"],
    ["utilized", "used"],
    ["utilising", "using"],
    ["utilizing", "using"],
    ["utilisation", "use"],
    ["utilization", "use"],
    ["viable", "workable"],
  ]),
];
