import type { ToolSource } from "../registry";

/**
 * API & HTTP tools. These are merged into the registry in lib/tools/registry.ts;
 * the long-form copy for each lives in content-api-http.ts.
 */
export const API_HTTP_TOOLS: Record<string, ToolSource> = {
  "http-status-code-lookup": {
    slug: "http-status-code-lookup",
    name: "HTTP Status Code Lookup",
    shortName: "HTTP Status Codes",
    tagline: "Look up any HTTP status code: meaning, causes and how to fix it.",
    category: "api-http",
    description: "Search every HTTP status code, including nginx and Cloudflare ones. See what it means, when it appears, how to fix it and whether it is safe to retry.",
    longDescription:
      "A searchable reference of HTTP status codes from 100 to 530. Each entry explains what the code means in plain language, when servers send it, the headers that go with it, how to fix the common error codes, and whether a client should retry. It includes the non-standard codes you meet in logs, such as nginx 499 and the Cloudflare 52x family.",
    iconName: "ListChecks",
    privacy: "local",
    metaTitle: "HTTP Status Code Lookup: Every Code Explained",
    metaDescription: "Look up any HTTP status code: 200, 301, 404, 429, 500, 502 and more. See what it means, why it happens and how to fix it. Free, instant, in your browser.",
    keywords: [
      "http status codes",
      "http status code list",
      "404 error meaning",
      "301 vs 302",
      "429 too many requests",
      "502 bad gateway",
      "503 service unavailable",
      "http response codes",
      "rest api status codes",
      "what does 403 mean",
    ],
    aliases: ["status code", "404", "500 error", "error codes", "response codes", "http errors", "301 redirect", "rate limit error"],
    features: [
      "Every registered code from 100 to 511, with current RFC 9110 names",
      "Non-standard codes too: nginx 444 and 499, Cloudflare 520 to 530, Laravel 419",
      "What it means, when it appears and how to fix it",
      "Headers that go with each code, cacheability and whether retrying is safe",
      "Search by number, name or word such as “timeout” or “redirect”",
      "Copy a link that opens a specific code",
    ],
    faqs: [
      {
        question: "What is the difference between 401 and 403?",
        answer: "401 Unauthorized means the request has no valid credentials: log in or send a correct token. 403 Forbidden means the server knows who you are, or does not care, and still refuses. Sending the same credentials again will not help with a 403.",
      },
      {
        question: "Should I use 301 or 302 for a redirect?",
        answer: "Use 301 (or 308) when a page has moved for good, so browsers and search engines update their records. Use 302 (or 307) for a temporary move, such as sending a signed-out visitor to a login page.",
      },
      {
        question: "Are the non-standard codes like 499 official?",
        answer: "No. They are defined by a specific server or service, such as nginx or Cloudflare, and they are marked as such here. They are real codes that appear in logs and error pages but are not part of the HTTP standard.",
      },
    ],
    relatedToolSlugs: ["http-header-viewer", "http-method-reference", "api-request-builder", "url-parser"],
    nextSteps: ["http-header-viewer", "api-request-builder", "http-method-reference"],
  },

  "http-header-viewer": {
    slug: "http-header-viewer",
    name: "HTTP Header Viewer & Analyzer",
    shortName: "HTTP Header Viewer",
    tagline: "Paste HTTP headers to see what each means and what to fix.",
    category: "api-http",
    description: "Paste request or response headers from curl, DevTools or logs. Each header is explained, security and caching problems are flagged, and cookies and CORS are checked.",
    longDescription:
      "Paste the headers from curl -I, your browser's Network tab or a server log and this tool explains every header in plain language. It checks the security headers (HSTS, CSP, X-Frame-Options, Referrer-Policy), reads Cache-Control and works out how long a response can be cached, inspects Set-Cookie flags, and spots CORS mistakes. It handles redirect chains from curl -L. Everything runs in your browser.",
    iconName: "TextSearch",
    privacy: "local",
    metaTitle: "HTTP Header Viewer & Security Checker",
    metaDescription: "Paste HTTP request or response headers to see what each one means. Checks security headers, Cache-Control, cookies and CORS. Free and private, in your browser.",
    keywords: [
      "http header viewer",
      "view http headers",
      "http headers checker",
      "security headers check",
      "analyze response headers",
      "cache-control explained",
      "curl -i output",
      "response header analyzer",
      "set-cookie flags",
      "http header parser",
    ],
    aliases: ["header checker", "check headers", "security headers", "response headers", "request headers", "curl headers", "explain headers"],
    features: [
      "Explains over 100 standard and common headers",
      "Security checklist: HSTS, CSP, nosniff, framing, referrer and permissions policy",
      "Cache-Control breakdown with how long a response may be reused",
      "Set-Cookie checks: Secure, HttpOnly, SameSite and __Host- rules",
      "CORS mistakes such as * with credentials",
      "Understands curl -i redirect chains and HTTP/2 headers",
    ],
    faqs: [
      {
        question: "Can this tool fetch the headers of a website for me?",
        answer: "No. A web page cannot read another site's response headers because of browser security rules. Run curl -I https://example.com or open your browser's Network tab, copy the headers and paste them here.",
      },
      {
        question: "Are the headers I paste sent anywhere?",
        answer: "No. They are parsed in your browser and never stored. Pasted headers are not saved, even locally, because they often contain cookies and tokens.",
      },
      {
        question: "What does the security checklist mean?",
        answer: "It shows whether six widely recommended response headers are present. A header being present is not proof it is configured well, so the findings below the checklist look at the actual values.",
      },
    ],
    relatedToolSlugs: ["http-header-generator", "http-status-code-lookup", "user-agent-parser", "jwt-decoder"],
    nextSteps: ["http-header-generator", "http-status-code-lookup", "jwt-decoder"],
  },

  "http-header-generator": {
    slug: "http-header-generator",
    name: "HTTP Header Generator",
    shortName: "HTTP Header Generator",
    tagline: "Generate security, CORS, cache and CSP headers for your server.",
    category: "api-http",
    description: "Build security headers, CORS headers, Cache-Control and a Content-Security-Policy, then copy them as config for nginx, Apache, Express, Netlify, Vercel and more.",
    longDescription:
      "Choose what you need and get valid headers with warnings for risky choices. Security headers include HSTS, X-Content-Type-Options, Referrer-Policy and Permissions-Policy; CORS lets you set an origin, methods and credentials; Cache-Control has presets for static files, HTML and APIs; the CSP builder covers every major directive. The result is written as configuration for nginx, Apache, Caddy, Express, Next.js, Netlify, Vercel, Firebase Hosting or IIS.",
    iconName: "SlidersHorizontal",
    privacy: "local",
    metaTitle: "HTTP Header Generator for Nginx, Apache & More",
    metaDescription: "Generate security, CORS, Cache-Control and CSP headers, then copy ready-made config for nginx, Apache, Express, Netlify, Vercel and Firebase. Free and private.",
    keywords: [
      "http header generator",
      "security headers generator",
      "cors headers generator",
      "cache-control generator",
      "content security policy generator",
      "nginx add_header",
      "apache header set",
      "csp builder",
      "hsts header",
      "firebase hosting headers",
    ],
    aliases: ["header builder", "csp generator", "cors config", "cache control builder", "security headers", "nginx headers", "htaccess headers"],
    features: [
      "Security headers with sensible defaults and warnings",
      "CORS builder that flags invalid combinations",
      "Cache-Control presets for static files, HTML, APIs and CDNs",
      "Content-Security-Policy builder for 14 directives, with presets",
      "Download headers with correct Content-Disposition for any file name",
      "Output for nginx, Apache, Caddy, Express, Next.js, Netlify, Vercel, Firebase and IIS",
    ],
    faqs: [
      {
        question: "Will these headers break my site?",
        answer: "They can if they are stricter than your site allows, especially Content-Security-Policy and Cross-Origin-Embedder-Policy. Start a CSP in report-only mode, test, then switch it on. The warnings under each result point to the options most likely to cause problems.",
      },
      {
        question: "Where do I paste the output?",
        answer: "The format menu tells you which file each one belongs in, such as nginx.conf, .htaccess, next.config.js, _headers or firebase.json. After changing server configuration, reload the server.",
      },
      {
        question: "Do you store the headers I generate?",
        answer: "No. Your choices are kept in your browser for a few days so the tool remembers them, and are never sent anywhere.",
      },
    ],
    relatedToolSlugs: ["http-header-viewer", "mime-type-lookup", "content-type-lookup", "http-method-reference"],
    nextSteps: ["http-header-viewer", "content-type-lookup", "http-method-reference"],
  },

  "user-agent-parser": {
    slug: "user-agent-parser",
    name: "User-Agent Parser",
    shortName: "User-Agent Parser",
    tagline: "Identify the browser, OS, device or bot behind a User-Agent.",
    category: "api-http",
    description: "Paste a User-Agent string to see the browser, version, engine, operating system and device. Detects crawlers, AI bots and HTTP clients, and parses many at once.",
    longDescription:
      "A User-Agent parser that reads the header the way modern browsers write it. It identifies the browser and version, rendering engine, operating system, CPU and device type, recognises search-engine crawlers, AI crawlers and API clients, and explains why every string starts with Mozilla/5.0. It warns when a value is unreliable, for example Chrome's frozen macOS version. Paste a log column to parse up to 500 strings at once, and see your own browser's details including Client Hints.",
    iconName: "MonitorSmartphone",
    privacy: "local",
    metaTitle: "User-Agent Parser: Browser, OS & Device",
    metaDescription: "Paste a User-Agent string to see the browser, version, engine, OS and device. Detects Googlebot, GPTBot and other bots. Parse many at once. Free and private.",
    keywords: [
      "user agent parser",
      "user agent string decoder",
      "what is my user agent",
      "parse user agent online",
      "detect browser from user agent",
      "googlebot user agent",
      "user agent bot detection",
      "navigator.useragent",
      "user agent client hints",
      "gptbot user agent",
    ],
    aliases: ["ua parser", "browser detector", "user agent checker", "what browser am i using", "useragent", "bot checker"],
    features: [
      "Browser, version, rendering engine, OS, CPU and device type",
      "Recognises search, AI and social crawlers and HTTP libraries",
      "Explains each part of the string and why it looks that way",
      "Warns about frozen or reduced values that cannot be trusted",
      "Parses up to 500 log lines at once, exportable as CSV",
      "Shows your own browser and its Client Hints",
    ],
    faqs: [
      {
        question: "Can I trust a User-Agent to identify a crawler?",
        answer: "Not on its own. Anyone can send a string that says Googlebot. To confirm a crawler is genuine, check the requesting IP against the operator's published ranges or do a reverse DNS lookup.",
      },
      {
        question: "Why does my Mac show as macOS 10.15.7 and Intel?",
        answer: "Browsers froze that part of the string to reduce fingerprinting, so every Mac reports 10.15.7 and Intel, including Apple Silicon machines on the latest macOS. Client Hints give the real values where supported.",
      },
      {
        question: "Why do all User-Agents start with Mozilla/5.0?",
        answer: "Early websites sent better pages to Netscape (code-named Mozilla), so every later browser claimed to be Mozilla-compatible. The string kept growing as each new browser named the engines it resembled.",
      },
    ],
    relatedToolSlugs: ["http-header-viewer", "url-parser", "http-status-code-lookup", "api-request-builder"],
    nextSteps: ["http-header-viewer", "url-parser", "api-request-builder"],
  },

  "url-parser": {
    slug: "url-parser",
    name: "URL Parser",
    shortName: "URL Parser",
    tagline: "Break a URL into scheme, host, port, path, query and fragment.",
    category: "api-http",
    description: "Paste any URL to see its scheme, host, port, path, query parameters and fragment, with problems flagged: bad encoding, credentials, secrets in the query string and more.",
    longDescription:
      "A URL parser that uses the same engine your browser does, so the parts you see are the parts a real request would use. It colour-codes the address, lists path segments and decoded query parameters, handles internationalised domain names, and flags common mistakes such as spaces, broken percent-escapes, credentials in the URL and tokens in the query string. You can edit any part and rebuild the URL with correct encoding, then copy code to parse it in JavaScript, Python, PHP or Go.",
    iconName: "ScanSearch",
    privacy: "local",
    metaTitle: "URL Parser: Break a URL into Its Parts",
    metaDescription: "Paste a URL to see its scheme, host, port, path, query parameters and fragment, with problems flagged. Edit any part and rebuild it. Free and private.",
    keywords: [
      "url parser",
      "parse url online",
      "url components",
      "extract query parameters from url",
      "url anatomy",
      "hostname from url",
      "url breakdown",
      "url checker",
      "url validator",
      "parse url javascript",
    ],
    aliases: ["split url", "url analyzer", "url inspector", "url parts", "get domain from url", "url path", "check url"],
    features: [
      "Colour-coded anatomy of the URL",
      "Scheme, host, port, origin, path segments, query and fragment",
      "Punycode and internationalised domain names decoded",
      "Warnings for spaces, bad encoding, credentials and secrets in the URL",
      "Edit any part and rebuild the URL with correct encoding",
      "Code to parse the same URL in JavaScript, Python, PHP and Go",
    ],
    faqs: [
      {
        question: "Is the fragment (#) sent to the server?",
        answer: "No. The part after # stays in the browser. That is why single-page apps and OAuth responses can use it without the server ever seeing it.",
      },
      {
        question: "What is the difference between a URL and a URI?",
        answer: "A URI identifies a resource; a URL is a URI that also says how to reach it, such as https://example.com/page. In everyday use the terms are interchangeable, and the web standard now calls everything a URL.",
      },
      {
        question: "Why does the parser change my URL?",
        answer: "It normalises it the way browsers do: host names are lower-cased, default ports are dropped and spaces or non-ASCII characters are percent-encoded. The normalised URL is what actually gets requested.",
      },
    ],
    relatedToolSlugs: ["query-parameter-parser", "query-string-builder", "url-encoder-decoder", "utm-builder"],
    nextSteps: ["query-parameter-parser", "url-encoder-decoder", "query-string-builder"],
  },

  "query-parameter-parser": {
    slug: "query-parameter-parser",
    name: "Query Parameter Parser",
    shortName: "Query Parser",
    tagline: "Turn a query string into a table or JSON, decoded.",
    category: "api-http",
    description: "Paste a query string or URL to get every parameter decoded, as a table or JSON. Handles repeated names, a[]=1 and a[b]=1, and flags tracking parameters.",
    longDescription:
      "Decode a query string into a readable table or a JSON object. Repeated names become arrays, bracket syntax such as color[]=red or filter[status]=open becomes nested data the way PHP, Rails and the qs library read it, and percent-encoding and plus signs are decoded correctly. Tracking parameters like utm_source and fbclid are identified, and you can strip them with one click. Copy code to read the same parameters in JavaScript, Python, PHP or curl.",
    iconName: "ListFilter",
    privacy: "local",
    metaTitle: "Query String Parser to Table & JSON",
    metaDescription: "Paste a query string or URL to decode every parameter into a table or JSON. Handles repeats, a[]=1 arrays and nested keys. Removes tracking parameters. Free.",
    keywords: [
      "query string parser",
      "parse query parameters",
      "url parameters to json",
      "query string to json",
      "get url parameters",
      "decode url parameters",
      "remove utm parameters",
      "url params parser",
      "urlsearchparams",
      "split query string",
    ],
    aliases: ["url parameters", "query params", "get params", "query string decoder", "parse params", "querystring to object"],
    features: [
      "Decoded table of every parameter, in order",
      "JSON output with arrays for repeated names",
      "Understands a[]=1, a[0]=1 and a[b]=1 nesting",
      "Plus-as-space and percent-decoding handled correctly",
      "Finds tracking parameters (UTM, fbclid, gclid…) and strips them",
      "Code for JavaScript, Python, PHP and curl",
    ],
    faqs: [
      {
        question: "How are repeated parameters handled?",
        answer: "It depends on the server. PHP keeps the last value unless the name ends in [], Express and many Node libraries build an array, and Flask and Go return all values through a separate call. This tool shows them all so you can see what was sent.",
      },
      {
        question: "Why does my value contain + signs?",
        answer: "In form-encoded query strings + means a space, so this tool decodes it that way by default. In URL paths a plus is a literal plus sign. The toggle switches between the two readings.",
      },
      {
        question: "Does removing tracking parameters change the page?",
        answer: "Almost never. Parameters like utm_source and fbclid only identify how a visitor arrived. Anything else in the query string is left exactly as it was.",
      },
    ],
    relatedToolSlugs: ["url-parser", "query-string-builder", "url-encoder-decoder", "utm-builder"],
    nextSteps: ["query-string-builder", "url-parser", "utm-builder"],
  },

  "query-string-builder": {
    slug: "query-string-builder",
    name: "Query String Builder",
    shortName: "Query Builder",
    tagline: "Build a correctly encoded query string from rows or JSON.",
    category: "api-http",
    description: "Build a URL query string from name and value rows or a JSON object. Choose array format, space encoding and sorting, then copy the result or code for it.",
    longDescription:
      "Add name and value rows, paste a JSON object, or import an existing query string, and get a correctly encoded result. Choose how arrays are written (repeated names, brackets, indexes or comma separated), whether spaces become %20 or +, and whether to sort and drop empty values. Add a base URL to get the full address. The same parameters are shown as code for JavaScript, Python, PHP and curl.",
    iconName: "Settings2",
    privacy: "local",
    metaTitle: "Query String Builder & URL Params Encoder",
    metaDescription: "Build a URL query string from name and value rows or JSON, with array formats, %20 or + spaces and sorting. Copy the result or the code. Free and private.",
    keywords: [
      "query string builder",
      "build url parameters",
      "object to query string",
      "json to query string",
      "urlencode params",
      "array query params format",
      "url parameters generator",
      "http_build_query",
      "urlsearchparams builder",
      "query params encoder",
    ],
    aliases: ["query builder", "params builder", "url params", "create query string", "encode parameters", "url query generator"],
    features: [
      "Name and value rows, JSON object or an imported query string",
      "Four array formats: repeat, brackets, indexed and comma",
      "%20 or + for spaces, full or minimal encoding",
      "Sort by name, skip empty values",
      "Optional base URL for a complete address",
      "Matching code for JavaScript, Python, PHP and curl",
    ],
    faqs: [
      {
        question: "Which array format should I use?",
        answer: "Whatever your server expects. Repeating the name (tag=a&tag=b) works for most frameworks. PHP and Rails prefer tag[]=a, and some APIs document comma-separated values. Check the API docs.",
      },
      {
        question: "Should spaces be %20 or +?",
        answer: "%20 is correct everywhere in a URL. + means a space only in form-encoded query strings, and most servers accept both there. When in doubt use %20.",
      },
      {
        question: "Does it encode the parameter names too?",
        answer: "Yes. Names are encoded like values, except that square brackets in array notation are left readable.",
      },
    ],
    relatedToolSlugs: ["query-parameter-parser", "url-parser", "url-encoder-decoder", "utm-builder"],
    nextSteps: ["url-parser", "url-encoder-decoder", "api-request-builder"],
  },

  "api-request-builder": {
    slug: "api-request-builder",
    name: "API Request Builder",
    shortName: "API Request Builder",
    tagline: "Build, send and inspect HTTP requests from your browser.",
    category: "api-http",
    description: "An online REST client: set the method, URL, headers, body and auth, send the request from your browser and inspect the response, then copy it as curl, fetch or Python.",
    longDescription:
      "Build an HTTP request with a method, URL, query parameters, headers, JSON, form or file body and Basic, Bearer or API-key authentication, then send it straight from your browser and read the status, timing, headers and body. If the request fails, the tool tells you whether the server answered but blocked the response (CORS) or could not be reached. Import a curl command, or export the request as curl, fetch, Axios or Python. Requests go directly from your browser to the address you enter.",
    iconName: "Send",
    privacy: "network",
    privacyNote: "Requests go directly from your browser to the address you enter. TabBench does not see or store them.",
    metaTitle: "Online API Request Builder & REST Client",
    metaDescription: "Build and send HTTP requests from your browser: set headers, body and auth, read the response, then copy as curl, fetch or Python. No install, no account.",
    keywords: [
      "api request builder",
      "online rest client",
      "http request tester",
      "test api online",
      "postman alternative online",
      "send get post request online",
      "api tester",
      "http client online",
      "rest api tester",
      "curl online",
    ],
    aliases: ["api tester", "rest client", "postman online", "send request", "http tester", "test endpoint", "api client"],
    features: [
      "Method, URL, query parameters, headers, JSON, form, multipart and file bodies",
      "Basic, Bearer token and API-key authentication",
      "Shows status, time, size, headers and body, with images rendered",
      "Explains CORS and connection failures instead of a blank error",
      "Import a curl command or export as curl, fetch, Axios and Python",
      "Runs in the browser with nothing to install",
    ],
    faqs: [
      {
        question: "Why does my request fail with a network error?",
        answer: "A browser only lets this page read a response if the server allows it with CORS headers. For a GET or HEAD the tool runs a second check to tell you whether the server answered but blocked the reply, or could not be reached at all. A terminal with curl is not limited by CORS.",
      },
      {
        question: "Can I call localhost or a private network?",
        answer: "Yes, if the server is running on your computer or network and sends CORS headers. Browsers allow https pages to call http://localhost, but block other plain http addresses as mixed content.",
      },
      {
        question: "Is it safe to put real tokens here?",
        answer: "Requests go from your browser directly to the server you name, so the server sees whatever you send. Nothing is saved by TabBench and the form is not stored. Use test credentials when you can, and clear any real token from the form after use.",
      },
    ],
    relatedToolSlugs: ["curl-generator", "curl-to-fetch", "http-header-viewer", "http-status-code-lookup"],
    nextSteps: ["curl-to-python", "http-header-viewer", "http-status-code-lookup"],
  },

  "curl-generator": {
    slug: "curl-generator",
    name: "cURL Command Generator",
    shortName: "cURL Generator",
    tagline: "Build a correct curl command from a form, for any shell.",
    category: "api-http",
    description: "Fill in the method, URL, headers, body and auth and get a correct curl command for Bash, PowerShell or cmd, with warnings about risky options. Convert to code in one click.",
    longDescription:
      "A curl command builder for people who do not remember the flags. Set the method, URL, parameters, headers, JSON, form, multipart or file body and authentication, and get a correctly quoted command for Bash and zsh, PowerShell (curl.exe) or Windows cmd. Options cover redirects, compression, timeouts and certificate checks, each with a plain explanation. Start from an existing curl command to edit it, and see the same request as fetch, Axios or Python.",
    iconName: "SquareTerminal",
    privacy: "local",
    metaTitle: "cURL Command Generator: Build Requests Online",
    metaDescription: "Build a curl command from a form: method, headers, JSON or form body, auth and options. Correct quoting for Bash, PowerShell and cmd. Free and private.",
    keywords: [
      "curl generator",
      "curl command builder",
      "generate curl command",
      "curl post json example",
      "curl with headers",
      "curl basic auth",
      "curl powershell",
      "curl multipart form data",
      "curl command online",
      "curl bearer token",
    ],
    aliases: ["curl builder", "make curl command", "curl maker", "curl command creator", "curl examples", "curl syntax"],
    features: [
      "Method, URL, parameters, headers and five body types",
      "Basic, Bearer and API-key auth",
      "Correct quoting for Bash/zsh, PowerShell and Windows cmd",
      "One option per line, short or long flags",
      "Warnings for passwords in commands, -k and GET with a body",
      "Start from an existing curl command; export as fetch, Axios or Python",
    ],
    faqs: [
      {
        question: "Why does PowerShell use curl.exe?",
        answer: "In Windows PowerShell 5, curl is an alias for Invoke-WebRequest, which takes different options. Calling curl.exe runs the real curl that ships with Windows 10 and later.",
      },
      {
        question: "What is the difference between -d and --data-urlencode?",
        answer: "-d sends the text exactly as written, which is right for JSON. --data-urlencode percent-encodes a value for you, which is right for form fields. The generator picks the correct one for the body type.",
      },
      {
        question: "Are my tokens and passwords stored?",
        answer: "No. The form is not saved anywhere and nothing is sent to a server. Be careful pasting the finished command into chat or tickets, because it contains your credentials.",
      },
    ],
    relatedToolSlugs: ["curl-to-fetch", "curl-to-python", "api-request-builder", "http-method-reference"],
    nextSteps: ["curl-to-fetch", "curl-to-python", "api-request-builder"],
  },

  "curl-to-fetch": {
    slug: "curl-to-fetch",
    name: "cURL to Fetch Converter",
    shortName: "cURL to Fetch",
    tagline: "Convert a curl command to JavaScript fetch code.",
    category: "api-http",
    description: "Paste a curl command, including “Copy as cURL” from DevTools, and get working JavaScript fetch code with async/await or .then(), proper body handling and error checks.",
    longDescription:
      "Convert any curl command to a fetch() call for browsers and Node.js 18+. It reads curl the way curl does, including combined flags, $'…' strings and the Windows cmd format Chrome produces, then writes clean code: JSON bodies become objects passed through JSON.stringify, forms become URLSearchParams, uploads become FormData and Basic auth becomes an Authorization header. It warns about what a browser will not let you do, such as setting the Cookie header, and what curl does that fetch does not.",
    iconName: "ArrowRightLeft",
    privacy: "local",
    metaTitle: "cURL to Fetch Converter (JavaScript)",
    metaDescription: "Convert a curl command to JavaScript fetch code for browsers and Node.js. Handles JSON, forms, uploads and auth, in async/await or .then() style. Free.",
    keywords: [
      "curl to fetch",
      "convert curl to fetch",
      "curl to javascript fetch",
      "curl to fetch api",
      "copy as curl to fetch",
      "curl command to fetch",
      "curl to js",
      "fetch from curl",
    ],
    aliases: ["curl fetch", "curl to fetch converter", "curl to js fetch", "convert curl", "devtools curl to fetch"],
    features: [
      "async/await or .then() chain",
      "JSON, urlencoded, multipart and file bodies",
      "Basic, Bearer and API-key headers",
      "Reads Bash, cmd and PowerShell style commands",
      "Notes on forbidden browser headers, CORS and redirects",
      "Verified against real curl on a local server",
    ],
    faqs: [
      {
        question: "Does the generated code work in Node.js?",
        answer: "Yes, on Node.js 18 and later, which include fetch. On older versions install a fetch polyfill such as node-fetch.",
      },
      {
        question: "Why is my Cookie or User-Agent header ignored in the browser?",
        answer: "Browsers do not let scripts set certain headers, including Cookie, Host and Referer, and ignore User-Agent. The tool lists which of your headers are affected. From Node.js or a server all of them work.",
      },
      {
        question: "Why does fetch behave differently from curl on redirects?",
        answer: "curl only follows redirects when you pass -L. fetch follows them by default. Turn on the option to match curl's behaviour if the difference matters.",
      },
    ],
    relatedToolSlugs: ["curl-to-axios", "curl-to-javascript", "curl-to-python", "curl-generator"],
    nextSteps: ["curl-to-axios", "api-request-builder", "curl-to-python"],
  },

  "curl-to-axios": {
    slug: "curl-to-axios",
    name: "cURL to Axios Converter",
    shortName: "cURL to Axios",
    tagline: "Convert a curl command to Axios code for JavaScript.",
    category: "api-http",
    description: "Paste a curl command and get Axios code: axios({…}) or axios.post() style, import or require, with headers, auth, bodies, timeouts and error handling.",
    longDescription:
      "Turn a curl command into an Axios request. Choose the config-object style or the shorthand methods such as axios.post(url, data, config), ES module import or CommonJS require, and keep or drop the try/catch around the call. JSON bodies become plain objects, forms become URLSearchParams, uploads use FormData, Basic auth uses Axios' auth option, -m becomes timeout and -k becomes an https agent for Node.js.",
    iconName: "ArrowRightLeft",
    privacy: "local",
    metaTitle: "cURL to Axios Converter for JavaScript",
    metaDescription: "Convert a curl command to Axios code: config or axios.post() style, import or require, with headers, auth, JSON and form bodies. Free and private.",
    keywords: [
      "curl to axios",
      "convert curl to axios",
      "curl to axios converter",
      "curl command to axios",
      "axios from curl",
      "curl to axios post",
      "curl to node axios",
      "curl to javascript axios",
    ],
    aliases: ["curl axios", "curl to axios request", "convert curl to axios code", "curl to js axios"],
    features: [
      "axios({ … }) config style or shorthand methods",
      "ES module import or CommonJS require",
      "Optional try/catch with axios.isAxiosError",
      "JSON, form, multipart and file bodies",
      "Basic auth, timeouts, redirects and https agent options",
      "Reads Bash, cmd and PowerShell quoting",
    ],
    faqs: [
      {
        question: "Do I need to install Axios?",
        answer: "Yes: run npm install axios. The code works in the browser and in Node.js.",
      },
      {
        question: "What does maxRedirects: 0 do?",
        answer: "It stops Axios following redirects, which matches curl when you did not pass -L. Axios follows up to five by default, so turn on “Match curl's redirect behaviour” only if you want that.",
      },
      {
        question: "How is -k handled?",
        answer: "In Node.js the code creates an https.Agent with rejectUnauthorized set to false. Browsers cannot skip certificate checks, so the option is Node-only and meant for testing.",
      },
    ],
    relatedToolSlugs: ["curl-to-fetch", "curl-to-javascript", "curl-to-python", "curl-generator"],
    nextSteps: ["curl-to-fetch", "api-request-builder", "curl-to-python"],
  },

  "curl-to-python": {
    slug: "curl-to-python",
    name: "cURL to Python Converter",
    shortName: "cURL to Python",
    tagline: "Convert a curl command to Python requests, httpx or urllib.",
    category: "api-http",
    description: "Paste a curl command and get Python code using requests, httpx or the standard-library urllib, with headers, JSON or form data, auth, files and timeouts.",
    longDescription:
      "Convert curl to Python in three flavours: requests, httpx, and urllib from the standard library for when you cannot install anything. JSON bodies become Python dicts passed as json=, forms become data=, uploads become files=, Basic auth becomes auth=(user, password), -m becomes timeout, -k becomes verify=False and -L maps to each library's redirect option. Notes explain the differences that matter, such as requests following redirects by default and httpx's five-second timeout.",
    iconName: "ArrowRightLeft",
    privacy: "local",
    metaTitle: "cURL to Python Converter: requests & urllib",
    metaDescription: "Convert a curl command to Python code with requests, httpx or urllib. Handles JSON, form data, file uploads, auth and timeouts. Free and runs in your browser.",
    keywords: [
      "curl to python",
      "convert curl to python requests",
      "curl to python converter",
      "curl command to python",
      "curl to requests",
      "curl to httpx",
      "curl to urllib",
      "python requests from curl",
    ],
    aliases: ["curl python", "curl to python requests", "curl to python code", "convert curl to python", "postman curl to python"],
    features: [
      "requests, httpx and standard-library urllib output",
      "JSON as json=, forms as data=, uploads as files=",
      "Auth, timeouts, proxies, redirects and verify=False",
      "Raise-for-status error handling",
      "Notes on differences from curl",
      "Reads Bash, cmd and PowerShell quoting",
    ],
    faqs: [
      {
        question: "Which library should I choose?",
        answer: "requests is the most widely used and is fine for most scripts. httpx adds async support and HTTP/2. urllib needs no installation but is more verbose and has no multipart helper.",
      },
      {
        question: "Why does the code send my JSON with json= instead of data=?",
        answer: "json= serialises the dict and sets the Content-Type header for you, which is what curl -H 'Content-Type: application/json' -d '{…}' does by hand. Bodies that are not valid JSON are sent as a string with data=.",
      },
      {
        question: "Does the converter run my request?",
        answer: "No. It only reads the command and writes code. Nothing is sent anywhere, and the curl text stays in your browser.",
      },
    ],
    relatedToolSlugs: ["curl-to-fetch", "curl-to-axios", "curl-to-javascript", "curl-generator"],
    nextSteps: ["curl-to-fetch", "api-request-builder", "curl-generator"],
  },

  "curl-to-javascript": {
    slug: "curl-to-javascript",
    name: "cURL to JavaScript Converter",
    shortName: "cURL to JavaScript",
    tagline: "Convert curl to fetch, XMLHttpRequest, Node.js https or jQuery.",
    category: "api-http",
    description: "Paste a curl command and get JavaScript code in your choice of fetch, XMLHttpRequest, the Node.js https module, jQuery $.ajax or Axios.",
    longDescription:
      "Convert curl to whichever JavaScript style your project uses: modern fetch, classic XMLHttpRequest, the built-in Node.js https module with no dependencies, jQuery's $.ajax, or Axios. The converter reads curl the way curl does and writes the matching idiom for each, with notes on what differs: browsers refuse some headers, Node's https module does not follow redirects, and jQuery needs processData settings for uploads.",
    iconName: "ArrowRightLeft",
    privacy: "local",
    metaTitle: "cURL to JavaScript Converter: Fetch, XHR, Node",
    metaDescription: "Convert a curl command to JavaScript: fetch, XMLHttpRequest, Node.js https, jQuery or Axios. Handles JSON, forms, uploads and auth. Free and private.",
    keywords: [
      "curl to javascript",
      "convert curl to javascript",
      "curl to xmlhttprequest",
      "curl to node.js",
      "curl to jquery ajax",
      "curl to js",
      "curl command to javascript",
      "curl to nodejs https",
    ],
    aliases: ["curl js", "curl to ajax", "curl to xhr", "curl to node", "convert curl to js"],
    features: [
      "fetch, XMLHttpRequest, Node.js https, jQuery and Axios output",
      "Headers, JSON, form and multipart bodies",
      "Basic auth, timeouts and certificate options where the target supports them",
      "Notes for each runtime's limits",
      "Zero-dependency Node.js version",
      "Verified against real curl on a local server",
    ],
    faqs: [
      {
        question: "Which JavaScript output should I use?",
        answer: "fetch for new browser and Node 18+ code. The Node.js https version when you want no dependencies on older Node. XMLHttpRequest and jQuery mainly for legacy browser code.",
      },
      {
        question: "Why does the Node.js https version not follow redirects?",
        answer: "The built-in http and https modules never follow redirects. Use fetch or Axios if you passed -L, or add a package such as follow-redirects.",
      },
      {
        question: "Can I send a file upload with the https module?",
        answer: "Building multipart bodies by hand is error-prone, so for uploads the converter falls back to fetch with FormData, which Node.js 18 and later include.",
      },
    ],
    relatedToolSlugs: ["curl-to-fetch", "curl-to-axios", "curl-to-python", "curl-generator"],
    nextSteps: ["curl-to-fetch", "curl-to-axios", "api-request-builder"],
  },

  "http-method-reference": {
    slug: "http-method-reference",
    name: "HTTP Method Reference",
    shortName: "HTTP Methods",
    tagline: "GET, POST, PUT, PATCH, DELETE: safe, idempotent, cacheable.",
    category: "api-http",
    description: "Compare HTTP methods by safety, idempotency, cacheability and request body, with REST usage, example requests and advice on PUT vs PATCH and POST vs GET.",
    longDescription:
      "A reference for every HTTP method, based on RFC 9110. See at a glance which methods are safe, which are idempotent and which can be cached, what a request body means for each, which success codes to expect and how each maps to a REST API. It covers GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS, TRACE and CONNECT, plus the WebDAV methods, with example requests and answers to the questions people actually ask, such as PUT or PATCH.",
    iconName: "BookOpen",
    privacy: "local",
    metaTitle: "HTTP Methods: GET, POST, PUT, PATCH, DELETE",
    metaDescription: "Compare HTTP methods: safe, idempotent, cacheable and body rules for GET, POST, PUT, PATCH, DELETE, OPTIONS and more. Examples and REST guidance.",
    keywords: [
      "http methods",
      "get vs post",
      "put vs patch",
      "idempotent http methods",
      "safe http methods",
      "http verbs",
      "options method cors",
      "rest api methods",
      "http methods reference",
      "delete request body",
    ],
    aliases: ["http verbs", "get post put delete", "rest verbs", "http request methods", "idempotent methods", "patch vs put"],
    features: [
      "Comparison table of safe, idempotent, cacheable and body rules",
      "Detail page for each method with notes and an example request",
      "Expected success codes linked to the status code lookup",
      "REST mapping for each method",
      "Answers: PUT or PATCH, POST or GET, which can be retried",
      "WebDAV methods included",
    ],
    faqs: [
      {
        question: "What does idempotent mean?",
        answer: "Sending the same request once or many times leaves the server in the same state. GET, PUT, DELETE, HEAD and OPTIONS are idempotent, which makes them safe to retry after a timeout. POST and PATCH generally are not.",
      },
      {
        question: "Is a safe method the same as a secure one?",
        answer: "No. “Safe” means read-only: the method does not change anything on the server. It says nothing about encryption or authentication.",
      },
      {
        question: "Can a GET request have a body?",
        answer: "The standard gives a body on GET no meaning, and many servers, proxies and libraries drop it. Use query parameters, or POST for large searches.",
      },
    ],
    relatedToolSlugs: ["http-status-code-lookup", "api-request-builder", "http-header-viewer", "curl-generator"],
    nextSteps: ["http-status-code-lookup", "api-request-builder", "curl-generator"],
  },

  "mime-type-lookup": {
    slug: "mime-type-lookup",
    name: "MIME Type Lookup",
    shortName: "MIME Types",
    tagline: "Find the MIME type for any file extension, and back.",
    category: "api-http",
    description: "Search MIME types by file extension or type. See the right Content-Type for PDF, JSON, PNG, SVG, MP4, DOCX and about 200 more, and which ones compress well.",
    longDescription:
      "Look up the MIME type (media type) for a file extension, or the extensions that use a type. The database covers about 200 common formats across text, code, images, audio, video, fonts, documents, archives, data and 3D, marks the ones that are not in the IANA registry, and tells you whether a type compresses well so you know whether to enable gzip or brotli for it. Copy a type in one click.",
    iconName: "FileSearch",
    privacy: "local",
    metaTitle: "MIME Type Lookup by File Extension",
    metaDescription: "Find the MIME type for any file extension, or the extensions for a type. About 200 formats: PDF, JSON, PNG, SVG, MP4, DOCX and more. Free and instant.",
    keywords: [
      "mime types list",
      "mime type by extension",
      "content type for pdf",
      "application/json mime type",
      "file extension to mime type",
      "mime type for docx",
      "mime type for svg",
      "mime type for mp4",
      "media types",
      "mime type lookup",
    ],
    aliases: ["mime types", "content type", "file type", "media type", "extension mime", "mime list"],
    features: [
      "About 200 extensions across 11 categories",
      "Search by extension, MIME type or word",
      "Reverse lookup: every extension for a type",
      "Marks unregistered x- types",
      "Compressibility hint for each type",
      "Copy a type in one click",
    ],
    faqs: [
      {
        question: "What is a MIME type?",
        answer: "A label in the form type/subtype, such as image/png or application/json, that tells software what kind of data a file or HTTP response contains. Servers send it in the Content-Type header.",
      },
      {
        question: "What is application/octet-stream?",
        answer: "The fallback for unknown binary data. Browsers do not try to display it; they offer to download it.",
      },
      {
        question: "Why is a type marked unregistered?",
        answer: "It is not in the IANA registry, usually because it is an older x- type or a format nobody registered. Servers and browsers still use it, so it is listed with that note.",
      },
    ],
    relatedToolSlugs: ["content-type-lookup", "http-header-generator", "http-header-viewer", "sample-file-generator"],
    nextSteps: ["content-type-lookup", "http-header-generator", "http-header-viewer"],
  },

  "content-type-lookup": {
    slug: "content-type-lookup",
    name: "Content-Type Lookup & Checker",
    shortName: "Content-Type Lookup",
    tagline: "Pick, check or detect the right Content-Type header.",
    category: "api-http",
    description: "Find the Content-Type to send for JSON, forms, uploads and downloads, check a header value for mistakes, or drop a file to detect its real type from its contents.",
    longDescription:
      "Three tools for the Content-Type header. The first lists what to send for the jobs you actually have: JSON APIs, problem details, forms and multipart uploads, web pages, SVG, WebAssembly, PDFs, downloads, server-sent events and more, with a note on each. The second checks a value you paste, reporting the type, parameters and mistakes such as a missing multipart boundary or text/json. The third reads the first bytes of a dropped file to find its true type, independent of the extension, and gives the header to serve it with.",
    iconName: "FileType",
    privacy: "local",
    metaTitle: "Content-Type Header Lookup & Checker",
    metaDescription: "Find the right Content-Type for JSON, forms, uploads and downloads, check a header for mistakes, or detect a file's real type from its bytes. Free, private.",
    keywords: [
      "content-type header",
      "content type application/json",
      "content-type multipart form-data boundary",
      "what content type to send",
      "check content type of file",
      "file signature detector",
      "magic number file type",
      "content-type charset utf-8",
      "text/event-stream",
      "content type checker",
    ],
    aliases: ["content type", "content-type checker", "mime detector", "file type detector", "header content type", "what is my file type"],
    features: [
      "Recipes for 30 common jobs, grouped: API, web page, files, streaming",
      "Header checker: type, subtype, suffix, charset, boundary and common mistakes",
      "File identifier that reads magic bytes, not the extension",
      "Warns when extension and contents disagree",
      "Header ready to copy for serving the file",
      "Files never leave your browser",
    ],
    faqs: [
      {
        question: "Do I set Content-Type on a multipart upload myself?",
        answer: "No. Let the browser or HTTP library set it. It must contain the boundary string used in the body, and setting the header by hand without the matching boundary breaks the upload.",
      },
      {
        question: "Does application/json need charset=utf-8?",
        answer: "No. JSON is always UTF-8, so the parameter is redundant. Text types such as text/html and text/plain should include a charset.",
      },
      {
        question: "How does file detection work?",
        answer: "Most formats start with a fixed byte pattern (“magic number”), for example PNG files begin with the bytes 89 50 4E 47. The tool reads the first few kilobytes of the file in your browser and matches them; nothing is uploaded.",
      },
    ],
    relatedToolSlugs: ["mime-type-lookup", "http-header-generator", "http-header-viewer", "api-request-builder"],
    nextSteps: ["mime-type-lookup", "http-header-generator", "api-request-builder"],
  },
};
