import type { ToolSource } from "../registry";

/** Coin, dice, number and picker tools. Long-form copy lives in content-random.ts. */
export const RANDOM_TOOLS: Record<string, ToolSource> = {
  "coin-flip": {
    slug: "coin-flip",
    name: "Coin Flip",
    shortName: "Coin Flip",
    tagline: "Flip a fair coin online: heads or tails, or flip many at once.",
    category: "random-fun",
    description: "Flip a fair virtual coin for heads or tails, or flip up to 100 at once. Rename the sides to Yes and No, see your streaks and keep a running tally.",
    longDescription:
      "A coin flip that is actually fair. Each toss uses your device's cryptographic random generator, so the result cannot be predicted or steered. Flip one coin or up to 100 at once, rename the two sides (Heads and Tails, Yes and No, Me and You) to settle a real decision, and watch the tally and longest streak build over a session. The animation respects your reduced-motion setting, and nothing is stored or sent anywhere.",
    iconName: "Coins",
    privacy: "local",
    metaTitle: "Coin Flip: Toss a Fair Coin Online",
    metaDescription: "Flip a fair coin online for heads or tails, or flip up to 100 at once. Rename the sides, track streaks and totals. Unbiased and private, in your browser.",
    keywords: [
      "coin flip",
      "flip a coin",
      "heads or tails",
      "coin toss online",
      "random coin flip",
      "flip a coin online",
      "flip multiple coins",
      "coin flipper",
      "yes or no coin",
      "virtual coin toss",
    ],
    aliases: ["toss a coin", "heads tails", "coin toss", "flip coin", "decision maker", "yes no", "coin flipper"],
    features: [
      "Fair 50/50 using the device's cryptographic random generator",
      "Flip 1 to 100 coins at once",
      "Rename the sides: Heads/Tails, Yes/No or anything else",
      "Running tally, percentages and longest streak",
      "Smooth flip animation that respects reduced motion",
      "No sign-up, nothing stored or sent",
    ],
    faqs: [
      {
        question: "Is this coin flip really 50/50?",
        answer: "Yes. Each flip takes one random bit from your device's cryptographic generator, so heads and tails are exactly equally likely and every flip is independent of the last.",
      },
      {
        question: "Why do I sometimes get long streaks?",
        answer: "Streaks are normal in random sequences. In 100 fair flips the longest run is usually six or seven in a row. A run does not make the opposite side more likely next time.",
      },
      {
        question: "Can I use it to make a real decision?",
        answer: "Yes. Rename the sides to your two options and flip. Many people notice how they feel about the result: if you are hoping for the other side, that is your answer.",
      },
    ],
    relatedToolSlugs: ["dice-roller", "random-number-generator", "random-name-picker", "password-generator"],
    nextSteps: ["dice-roller", "random-name-picker", "random-number-generator"],
  },

  "dice-roller": {
    slug: "dice-roller",
    name: "Dice Roller",
    shortName: "Dice Roller",
    tagline: "Roll d4, d6, d20, d100 or any dice notation like 4d6kh3.",
    category: "random-fun",
    description: "Roll one or many dice online: d4, d6, d8, d10, d12, d20, d100. Supports notation such as 2d6+3, advantage, keep highest, exploding dice and shows the odds.",
    longDescription:
      "Roll any standard die or use full tabletop dice notation: 2d6+3, 4d6kh3 to drop the lowest, 2d20kh1 for advantage, 1d6! for exploding dice, d% for percentile and dF for Fate dice. Results show each die with dropped dice struck through, the total, the possible range and the average, and for ordinary rolls a chart of the exact probability of every total. Every roll is fair, drawn from your device's cryptographic random generator.",
    iconName: "Dices",
    privacy: "local",
    metaTitle: "Dice Roller: d4, d6, d20 and Custom Notation",
    metaDescription: "Roll dice online: d4 to d100 or notation like 2d6+3, 4d6kh3 and advantage. See each die, the total and the exact odds. Fair and private. Free to use.",
    keywords: [
      "dice roller",
      "roll a dice",
      "online dice",
      "d20 roller",
      "dnd dice roller",
      "roll 2d6",
      "dice notation",
      "random dice",
      "roll advantage d20",
      "dice probability",
    ],
    aliases: ["roll dice", "toss dice", "throw dice", "roll a die", "die roll", "dice", "d6", "d20", "dnd dice", "2d6", "virtual dice", "tabletop dice", "ability score roll"],
    features: [
      "d4, d6, d8, d10, d12, d20 and d100",
      "Notation: NdS±M, keep highest/lowest, exploding, d% and Fate dice",
      "Presets for advantage, disadvantage and ability scores",
      "Dropped dice struck through; shows range and average",
      "Exact probability chart for each total",
      "Roll history; fair, cryptographic randomness",
    ],
    faqs: [
      {
        question: "What does 4d6kh3 mean?",
        answer: "Roll four six-sided dice and keep the highest three. It is the classic way to generate a D&D ability score, because dropping the lowest die nudges the average up.",
      },
      {
        question: "How does advantage work?",
        answer: "Roll two d20 and take the higher (2d20kh1). Disadvantage takes the lower (2d20kl1). Advantage raises the chance of hitting a target number by up to about 25 percentage points, most when the target is near 11.",
      },
      {
        question: "Are the dice fair?",
        answer: "Yes. Each die is an unbiased random integer from your device's cryptographic generator, produced without the small bias that comes from the common shortcut of using modulo.",
      },
    ],
    relatedToolSlugs: ["coin-flip", "random-number-generator", "random-name-picker", "stopwatch-timer"],
    nextSteps: ["coin-flip", "random-number-generator", "random-name-picker"],
  },

  "random-number-generator": {
    slug: "random-number-generator",
    name: "Random Number Generator",
    shortName: "Random Numbers",
    tagline: "Generate fair random numbers: ranges, no repeats, decimals, PINs.",
    category: "random-fun",
    description: "Generate random numbers in any range: whole numbers or decimals, with or without repeats, sorted or as drawn. Presets for lottery picks, PINs and OTP-style codes.",
    longDescription:
      "Pick a range and how many numbers you want, and get unbiased random results. Choose whole numbers or decimals, turn off repeats for lottery-style draws, sort the output and pad with leading zeros for PINs and codes. Presets cover 1 to 10, 1 to 100, six numbers from 49, four-digit PINs and six-digit codes. The numbers come from your device's cryptographic random generator using rejection sampling, so none of the values is even slightly favoured.",
    iconName: "Dice5",
    privacy: "local",
    metaTitle: "Random Number Generator (Fair, No Repeats)",
    metaDescription: "Generate random numbers in any range, with or without repeats, as whole numbers or decimals. Presets for lottery picks and PINs. Unbiased and private.",
    keywords: [
      "random number generator",
      "random number between 1 and 100",
      "lottery number generator",
      "unique random numbers",
      "random pin generator",
      "rng",
      "random number picker",
      "random integer generator",
      "random decimal generator",
      "pick a random number",
    ],
    aliases: ["random number", "rng", "number picker", "random numbers", "lottery picker", "random int", "number generator"],
    features: [
      "Any range, up to 10,000 numbers at once",
      "Whole numbers or up to 10 decimal places",
      "No-repeats mode for draws and lotteries",
      "Sort low to high, high to low or as drawn",
      "Leading zeros for PINs and codes",
      "Sum, average, smallest and largest shown",
    ],
    faqs: [
      {
        question: "Are these numbers truly random?",
        answer: "They come from your device's cryptographic random generator, which is seeded from hardware and operating-system entropy. That is the same source used to create encryption keys, and it is far better than the Math.random() most simple generators use.",
      },
      {
        question: "Can I use it to pick lottery numbers?",
        answer: "Yes: choose the range, ask for the count and turn on No repeats. It cannot improve your odds, because every combination is equally likely, but it does avoid the human habit of choosing birthdays.",
      },
      {
        question: "Is it safe for generating a PIN?",
        answer: "Yes for a one-off PIN or code, since the numbers are cryptographically random and nothing is sent anywhere. For passwords use the Password Generator instead.",
      },
    ],
    relatedToolSlugs: ["dice-roller", "coin-flip", "random-name-picker", "password-generator"],
    nextSteps: ["random-name-picker", "password-generator", "dice-roller"],
  },

  "random-name-picker": {
    slug: "random-name-picker",
    name: "Random Name Picker & Wheel",
    shortName: "Name Picker",
    tagline: "Spin a wheel, draw winners or split names into teams.",
    category: "random-fun",
    description: "Paste a list of names or options, then spin the wheel, draw one or more winners or split everyone into balanced teams. Fair, private and works offline in your browser.",
    longDescription:
      "Type or paste names, one per line, and choose how to pick: spin a wheel for a single winner, draw several winners at once with no repeats, or shuffle everyone into teams of a size or number you choose. The winner is decided with a cryptographically secure draw before the wheel starts turning, so the animation never influences the result. Remove winners automatically for raffles, and copy results in one click. Your list stays in your browser.",
    iconName: "Trophy",
    privacy: "local",
    metaTitle: "Random Name Picker & Spin the Wheel",
    metaDescription: "Pick a random name, spin a wheel, draw multiple winners or make fair random teams from a list. Unbiased and private, in your browser. Free, no sign-up.",
    keywords: [
      "random name picker",
      "wheel of names",
      "spin the wheel",
      "team generator",
      "random team maker",
      "raffle winner picker",
      "pick a random winner",
      "random picker wheel",
      "giveaway winner picker",
      "random group maker",
    ],
    aliases: ["name picker", "wheel spinner", "random winner", "team splitter", "raffle", "giveaway picker", "random selector"],
    features: [
      "Spinning wheel with up to 500 entries",
      "Draw 1 to many winners with no repeats",
      "Split into teams by number of teams or people per team",
      "Remove each winner after the spin for raffles",
      "Winner chosen fairly before the animation starts",
      "Reduced-motion friendly; list saved only in your browser",
    ],
    faqs: [
      {
        question: "Is the wheel fair, or does it favour some slices?",
        answer: "It is fair. The winner is picked first by an unbiased random draw, and the wheel is then rotated to land on that slice. Every entry has the same chance regardless of where it sits or how big its label is.",
      },
      {
        question: "What if a name appears twice?",
        answer: "Each line is a separate entry, so a repeated name gets extra chances. The tool tells you when it finds repeats so you can remove them if that is not what you want.",
      },
      {
        question: "How are teams balanced?",
        answer: "The list is shuffled and dealt out one at a time to each team in turn, so team sizes never differ by more than one person.",
      },
    ],
    relatedToolSlugs: ["coin-flip", "dice-roller", "random-number-generator", "text-sorter"],
    nextSteps: ["coin-flip", "dice-roller", "text-sorter"],
  },
};
