import type { ToolSource } from "../registry";

/** Timers and clocks, the internet speed test and the regex builder. Long-form copy lives in content-time-and-more.ts. */
export const TIME_AND_MORE_TOOLS: Record<string, ToolSource> = {
  "countdown-timer": {
    slug: "countdown-timer",
    name: "Countdown Timer",
    shortName: "Countdown Timer",
    tagline: "Run several countdown timers with an alarm, or count down to a date.",
    category: "date-time",
    description: "Set one or more countdown timers with an alarm, notification and tab-title countdown, or count the days, hours and minutes to a date. Survives a page reload.",
    longDescription:
      "A countdown timer that keeps working when you switch tabs. Run up to six timers at once, each with its own label, set by hours, minutes and seconds or by typing a time like 25 min or 1h 15m. When time is up it rings, vibrates on phones and can show a notification, and the remaining time appears in the browser tab's title. A second mode counts down to a date and time, such as New Year or an exam, in days, hours, minutes and seconds. Running timers survive a reload.",
    iconName: "Hourglass",
    privacy: "local",
    metaTitle: "Online Countdown Timer with Alarm",
    metaDescription: "Free online countdown timer with alarm: run several timers at once, see the time in the tab title, or count down to a date. Works in the background, private.",
    keywords: [
      "countdown timer",
      "online timer",
      "timer with alarm",
      "kitchen timer online",
      "countdown to date",
      "multiple timers",
      "exam timer",
      "5 minute timer",
      "10 minute timer",
      "days until",
    ],
    aliases: ["timer", "egg timer", "countdown", "alarm timer", "cooking timer", "class timer", "days countdown", "count down", "online timer", "set a timer"],
    features: [
      "Up to six timers at once, each with a label",
      "Set with hours, minutes and seconds or type 25 min, 1h 15m",
      "Alarm sound, vibration and optional notification",
      "Time left shown in the browser tab title",
      "Keeps running in a background tab and after a reload",
      "Count down to any date and time, with holiday shortcuts",
    ],
    faqs: [
      {
        question: "Will the timer ring if I switch to another tab?",
        answer: "Yes. The timer counts from the clock, not from ticks, and uses a background worker so the browser cannot slow it down. The alarm is played by the page, so keep the tab open. Closing the tab stops the alarm, but the timer resumes correctly if you reopen the page.",
      },
      {
        question: "Why do I have to allow sound or notifications?",
        answer: "Browsers only play sound after you interact with the page, which pressing Start counts as. Notifications need your permission, which is asked only when you switch that option on.",
      },
      {
        question: "Is the date countdown in my time zone?",
        answer: "Yes. The date and time you pick are read in your device's time zone, so it counts down to that moment wherever you are.",
      },
    ],
    relatedToolSlugs: ["stopwatch-timer", "pomodoro-timer", "interval-timer", "world-clock"],
    nextSteps: ["pomodoro-timer", "interval-timer", "stopwatch-timer"],
  },

  "pomodoro-timer": {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    shortName: "Pomodoro Timer",
    tagline: "25/5 focus and break cycles with a daily session counter.",
    category: "date-time",
    description: "A Pomodoro timer with focus sessions, short and long breaks, automatic cycling, a daily goal and alerts. Customise the lengths or start from 25/5, 50/10 or 90/20.",
    longDescription:
      "The Pomodoro Technique alternates focused work with short breaks, and a longer break every few sessions. This timer runs the cycle for you: a focus session, a short break, and a long break after every fourth focus session (all adjustable). It rings when a phase ends, can start the next one automatically, counts today's completed sessions against a goal and puts the time in the tab title. Your settings and progress stay on your device.",
    iconName: "Coffee",
    privacy: "local",
    metaTitle: "Pomodoro Timer: 25/5 Focus and Break Cycles",
    metaDescription: "Free Pomodoro timer with focus sessions, short and long breaks, auto-start, a daily goal and alerts. Presets for 25/5, 50/10 and 90/20. Private, no sign-up.",
    keywords: [
      "pomodoro timer",
      "pomodoro technique",
      "25 5 timer",
      "study timer",
      "focus timer",
      "work timer with breaks",
      "pomodoro online",
      "50 10 timer",
      "pomodoro study",
      "productivity timer",
    ],
    aliases: ["pomodoro", "focus timer", "study timer", "work break timer", "25 minute timer", "tomato timer", "deep work timer"],
    features: [
      "Focus, short break and long break, all adjustable",
      "Presets: classic 25/5, deep work 50/10, short 15/3, 90/20",
      "Auto-start the next phase or start by hand",
      "Today's session count against a daily goal",
      "Alarm, optional notification and time in the tab title",
      "Full-screen mode; keeps the screen on while running",
    ],
    faqs: [
      {
        question: "What is the Pomodoro Technique?",
        answer: "Work in focused 25-minute blocks separated by 5-minute breaks, and take a longer break of 15 to 30 minutes after four blocks. It was developed by Francesco Cirillo in the late 1980s and named after his tomato-shaped kitchen timer.",
      },
      {
        question: "Can I change the 25 and 5 minutes?",
        answer: "Yes. Choose a preset or set any focus, short break and long break length, and how many focus sessions come before a long break. Longer blocks such as 50/10 or 90/20 suit deep work better than 25/5 for some people.",
      },
      {
        question: "Does it keep my progress if I close the page?",
        answer: "Settings, the current phase and today's count are saved in your browser for a few days. If a phase ended while the page was closed, it moves on to the next when you return.",
      },
    ],
    relatedToolSlugs: ["countdown-timer", "interval-timer", "stopwatch-timer", "notepad"],
    nextSteps: ["countdown-timer", "interval-timer", "notepad"],
  },

  "interval-timer": {
    slug: "interval-timer",
    name: "HIIT & Tabata Interval Timer",
    shortName: "Interval Timer",
    tagline: "Work and rest intervals with tones: Tabata, HIIT, EMOM, boxing.",
    category: "date-time",
    description: "An interval timer for Tabata, HIIT, EMOM, boxing rounds and circuits. Set work, rest, rounds and sets, hear tones for each change, and run it full screen.",
    longDescription:
      "Build a workout from a get-ready period, work and rest intervals, rounds, sets and a cool-down, or start from Tabata (20 seconds on, 10 off, eight rounds), HIIT 30/30, EMOM, three-minute boxing rounds or a circuit. The display shows the current interval in large type with the round and set, what comes next and total time left. Tones mark each change and count down the last three seconds. Skip and go back, pause, and run full screen on a phone or TV.",
    iconName: "Dumbbell",
    privacy: "local",
    metaTitle: "Interval Timer for HIIT, Tabata & EMOM",
    metaDescription: "Free interval timer for Tabata, HIIT, EMOM and boxing: set work, rest, rounds and sets, with tones and a full-screen display. Works offline, private.",
    keywords: [
      "interval timer",
      "tabata timer",
      "hiit timer",
      "emom timer",
      "workout timer",
      "boxing round timer",
      "circuit timer",
      "tabata 20 10",
      "rounds timer",
      "exercise interval timer",
    ],
    aliases: ["tabata", "hiit", "emom", "workout timer", "round timer", "boxing timer", "gym timer", "circuit training timer"],
    features: [
      "Get ready, work, rest, rounds, sets, set break and cool-down",
      "Presets: Tabata, HIIT 30/30, EMOM, boxing, circuit",
      "Tones at each change and a three-second countdown",
      "Large full-screen display with round, set and next interval",
      "Pause, skip forward and back",
      "Clock-accurate: skipping and pausing never drift",
    ],
    faqs: [
      {
        question: "What is Tabata?",
        answer: "A high-intensity interval protocol of 20 seconds of all-out effort and 10 seconds of rest, repeated for 8 rounds (4 minutes). It is named after Izumi Tabata, the Japanese researcher whose 1996 study tested the protocol.",
      },
      {
        question: "What does EMOM mean?",
        answer: "“Every minute on the minute”: you start a set of work at the top of each minute, and whatever time is left in the minute is your rest. Set work to 60 seconds and rest to 0, and the timer sounds at each minute.",
      },
      {
        question: "Will it keep time if my phone screen locks?",
        answer: "The timer works from the clock, so it stays accurate, and it asks your browser to keep the screen on while running. If the screen does lock, tones can be delayed by the browser, so keep the screen on during a workout.",
      },
    ],
    relatedToolSlugs: ["stopwatch-timer", "countdown-timer", "pomodoro-timer", "bmi-calculator"],
    nextSteps: ["stopwatch-timer", "bmi-calculator", "countdown-timer"],
  },

  "world-clock": {
    slug: "world-clock",
    name: "World Clock & Meeting Planner",
    shortName: "World Clock",
    tagline: "See the time in any city and find a meeting time across time zones.",
    category: "date-time",
    description: "Compare the current time across cities and time zones, with daylight saving handled, and use the meeting planner to find hours that fall within everyone's working day.",
    longDescription:
      "Add the cities you work with and see each one's current time, date, UTC offset and whether daylight saving is in force, with a clear sun or moon so you know who is asleep. The meeting planner lays out a day hour by hour for every city and shades working hours, so the best slot for everyone stands out; click an hour for the exact time in each place and copy the schedule. Time zone data comes from your browser's IANA database, so it follows the real rules for any date.",
    iconName: "Globe",
    privacy: "local",
    metaTitle: "World Clock & Time Zone Meeting Planner",
    metaDescription: "Free world clock: see the time in any city, compare time zones and find a meeting time that works for everyone. Handles daylight saving. Private, no sign-up.",
    keywords: [
      "world clock",
      "time zone converter",
      "meeting planner",
      "time difference",
      "current time in",
      "time zones",
      "convert time between cities",
      "meeting time across time zones",
      "world time",
      "utc converter",
    ],
    aliases: ["time zone", "time zones", "time difference calculator", "world time", "what time is it in", "current time in", "time in tokyo", "time in london", "time in new york", "time in dubai", "time in sydney", "ist to est", "timezone converter", "meeting scheduler", "utc time"],
    features: [
      "Live clocks for any cities or IANA time zones",
      "UTC offset, abbreviation and daylight-saving status",
      "Meeting planner that highlights shared working hours",
      "Choose the day, the base time zone and the working hours",
      "Copy the schedule for any hour",
      "12 or 24-hour display, with or without seconds",
    ],
    faqs: [
      {
        question: "Does it handle daylight saving time?",
        answer: "Yes. Offsets come from your browser's time-zone database and follow the actual rules for the date you pick, including the different dates countries switch. The planner shows the correct local time even across a change.",
      },
      {
        question: "What time zone does it use as my own?",
        answer: "Your device's time zone, read from the browser. It is shown as the first clock, and the planner uses it as the base by default.",
      },
      {
        question: "Why are some cities listed together, like Delhi / Mumbai?",
        answer: "Cities that share a time zone show one clock. All of India uses a single zone, UTC+5:30, so one entry covers every Indian city.",
      },
    ],
    relatedToolSlugs: ["unix-timestamp-converter", "countdown-timer", "date-difference-calculator", "working-days-calculator"],
    nextSteps: ["unix-timestamp-converter", "countdown-timer", "working-days-calculator"],
  },

  "internet-speed-test": {
    slug: "internet-speed-test",
    name: "Internet Speed Test",
    shortName: "Speed Test",
    tagline: "Test your download, upload, ping and jitter in about 15 seconds.",
    category: "api-http",
    description: "Measure your internet download and upload speed, latency, jitter and how responsive the connection stays under load. Quick and full tests, with what your speed is good for.",
    longDescription:
      "An internet speed test that runs in your browser against Cloudflare's public test servers. It measures idle latency and jitter, download and upload speed using parallel streams, and latency under load, which reveals bufferbloat, the lag that appears when someone else is downloading. Results show what your speed supports: streaming, video calls, gaming and uploads. A Quick test uses roughly 90 MB; the Full test is better for gigabit connections and can use several hundred MB.",
    iconName: "Gauge",
    privacy: "network",
    privacyNote: "Runs a test against Cloudflare's speed-test servers, which see your IP address like any website you visit. Nothing you type is involved, and results stay on your device.",
    metaTitle: "Internet Speed Test: Download, Upload & Ping",
    metaDescription: "Test your internet speed: download, upload, ping, jitter and bufferbloat in about 15 seconds. See what your connection can handle. Free, no app, private.",
    keywords: [
      "internet speed test",
      "speed test online",
      "check internet speed",
      "download speed test",
      "upload speed test",
      "ping test",
      "wifi speed test",
      "bufferbloat test",
      "mbps test",
      "how fast is my internet",
    ],
    aliases: ["speed test", "speedtest", "internet speedtest", "wifi speed", "my internet speed", "how fast is my internet", "broadband speed test", "net speed", "download speed", "upload speed", "bandwidth test", "latency test", "ping", "jitter test", "mbps"],
    features: [
      "Download and upload speed using parallel streams",
      "Latency (ping) and jitter",
      "Latency under load, to detect bufferbloat",
      "Quick test (about 15 seconds, about 90 MB) or Full test for fast lines",
      "What your speed is good for: streaming, calls, gaming, uploads",
      "Mbps or MB/s; recent results kept only on your device",
    ],
    faqs: [
      {
        question: "Why is my result lower than the speed my provider advertises?",
        answer: "Advertised speeds are maximums. Results depend on Wi-Fi signal, other devices, your router, time of day, a VPN and the route to the test server. For the best reading, use a cable, pause other downloads and run the Full test.",
      },
      {
        question: "What is the difference between Mbps and MB/s?",
        answer: "Providers quote megabits per second (Mbps); file downloads show megabytes per second (MB/s). There are 8 bits in a byte, so 100 Mbps is at most 12.5 MB/s. Use the unit switch to see either.",
      },
      {
        question: "How much data does the test use?",
        answer: "The Quick test moves up to about 90 MB in total and is fine for most connections. The Full test runs longer and can use several hundred megabytes on a fast line, so avoid it on mobile data.",
      },
    ],
    relatedToolSlugs: ["api-request-builder", "http-status-code-lookup", "world-clock", "stopwatch-timer"],
    nextSteps: ["api-request-builder", "http-header-viewer", "stopwatch-timer"],
  },

  "regex-builder": {
    slug: "regex-builder",
    name: "Regex Builder",
    shortName: "Regex Builder",
    tagline: "Build a regular expression from blocks, with live matches.",
    category: "developer",
    description: "Build a regular expression visually: add blocks such as digits, letters, text and groups, set how many times each repeats, and watch live matches. Exports to 8 languages.",
    longDescription:
      "Assemble a regular expression from plain-language blocks instead of writing syntax: text, digits, letters, character sets, “one of” options, groups, look-arounds and anchors, each with a repeat count. The expression and a plain-English reading update as you build, matches are highlighted in your test text as you go, and literal text is escaped for you. Start from 14 templates (email, dates, phone numbers, PAN, URLs, passwords) and export the result as code for JavaScript, Python, PHP, Java, C#, Go, Ruby or Rust.",
    iconName: "Blocks",
    privacy: "local",
    metaTitle: "Regex Builder: Build a Regular Expression",
    metaDescription: "Build a regular expression from blocks, no syntax needed: digits, text, groups and repeats with live highlighted matches. Export to JavaScript, Python and more.",
    keywords: [
      "regex builder",
      "regex generator",
      "build regex online",
      "regular expression builder",
      "regex creator",
      "email regex",
      "phone number regex",
      "regex without coding",
      "visual regex builder",
      "regex helper",
    ],
    aliases: ["regex maker", "create regex", "regex wizard", "regular expression generator", "regex helper", "regex designer", "make a regex"],
    features: [
      "Blocks for text, digits, letters, sets, options, groups and look-arounds",
      "Repeat counts: optional, one or more, exactly N, between N and M, lazy",
      "Plain-English reading of the expression as you build",
      "Live highlighted matches in your test text",
      "14 templates: email, date, time, mobile, PAN, URL, hex colour, password…",
      "Export to JavaScript, Python, PHP, Java, C#, Go, Ruby and Rust",
    ],
    faqs: [
      {
        question: "Do I need to know regular expressions to use it?",
        answer: "No. Each block is something you can say in words, such as “2 to 4 digits” or “the text https://”. The generated expression and its plain-English reading let you pick up the syntax as you go.",
      },
      {
        question: "Why is my text escaped with backslashes?",
        answer: "Characters such as . ? ( ) + * [ ] have special meaning in regular expressions. The Text block escapes them so they match literally. You never have to add the backslashes yourself.",
      },
      {
        question: "Can I keep editing in the Regex Tester?",
        answer: "Yes. “Open in the Regex Tester” carries the pattern, flags and your test text across, where you can also test replace and split, and read the full explanation.",
      },
    ],
    relatedToolSlugs: ["regex-tester", "text-diff-checker", "slug-generator", "json-formatter"],
    nextSteps: ["regex-tester", "text-diff-checker", "json-formatter"],
  },
};
